steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/animeta-frontend', '-f', 'Dockerfile.frontend', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '-v', '/workspace:/workspace', '--entrypoint', '/bin/bash', 'gcr.io/$PROJECT_ID/animeta-frontend',
          '-c', 'cp -r /app/animeta/static /workspace/' ]
- name: 'gcr.io/cloud-builders/gsutil'
  args: [ '-m', 'cp', '-r', 'static', 'gs://animeta-static/' ]
images:
- 'gcr.io/$PROJECT_ID/animeta-frontend'
