version: "3.4"
services:
  backend:
    image: sapzilorg/animeta-backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    configs:
      - source: spring
        target: /app/application.properties
      - source: google_credentials
        target: /app/google-credentials.json
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/application.properties
    ports:
      - target: 8080
        published: 8080
        mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  frontend:
    image: quay.io/dittos/animeta:master
    depends_on:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    volumes:
      - "static:/app/static"
    configs:
      - source: frontend
        target: /app/frontend-dist/config.json
    environment:
      - PORT=3000
    ports:
      - target: 3000
        published: 3000
        mode: ingress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
configs:
  spring:
    file: ./application.properties
  google_credentials:
    file: ./google-credentials.json
  frontend:
    file: ./frontend.json
volumes:
  static:
