name: Backend (TS) / CI

on:
  push:
    branches: [ '*' ]
    paths:
      - 'backend-ts/**'
      - 'tooling/**'
      - '.github/workflows/backend-ts-ci.yml'
  pull_request:
    paths: ['backend-ts/**', 'tooling/**']

jobs:
  test:

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: .

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - run: pnpm -C tooling run build
    - run: pnpm -C backend-ts run prebuild && pnpm -C backend-ts run build
    
    - name: Run unit tests
      run: pnpm -C backend-ts run test

    - name: Run functional tests
      run: pnpm -C backend-ts run test:e2e
